### ISSUE TITLE
ReferenceError: robot is not defined

### ISSUE THREAD

**Issue by david4shure** [hubot-scripts/hubot-github-repo-event-notifier#48]
When I use hubot-github-repo-event-notifier version 1.8 I get the following error when I start my hubot instance.

```
ERROR Unable to load /app/node_modules/hubot-github-repo-event-notifier/src/github-repo-event-notifier: ReferenceError: robot is not defined
at Object.<anonymous> (/app/node_modules/hubot-github-repo-event-notifier/src/github-repo-event-notifier.coffee:61:3, <js>:33:5)
at Object.<anonymous> (/app/node_modules/hubot-github-repo-event-notifier/src/github-repo-event-notifier.coffee:37:1, <js>:90:4)
at Module._compile (module.js:570:32)
at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Robot.loadFile (/app/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
at /app/node_modules/hubot-github-repo-event-notifier/index.coffee:12:11, <js>:26:33
at FSReqWrap.cb [as oncomplete] (fs.js:258:19)
```

This error occurs when I am running version 1.8.0. If I switch to 1.7.0, everything works fine on startup. The dangers of using version `>= 0.0.0` in my `package.json` I suppose. 

Anyways, I am running on OSX, but have tested this both inside a docker container as well as natively with the same result.

**Comment by strugee** [comment]
Yikes! That's no good.

This is definitely my fault; this is what I get for shipping without fully/properly testing 🙄 

I'd love to fix the original issue permanently, but in the meantime I'll back out the relevant commit. A patch release will be on npm shortly.
